version: '3.7'

services:
  create_cert:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    command: >
      bash -c '

        if [[ ! -f /certs/elasticsearch.p12 || \
              ! -f /certs/kibana.zip ]]; then
          echo "Removing certificates" &&
          rm -rf /certs/* &&

          echo "Generating CA" &&
          bin/elasticsearch-certutil ca --silent --pass QwerTy  --pem --out /certs/ca.zip &&
          unzip /certs/ca.zip -d /certs &&

          echo "Generating certificate for Elasticsearch" &&
          bin/elasticsearch-certutil cert --silent --ca-cert /certs/ca/ca.crt --ca-key /certs/ca/ca.key --ca-pass QwerTy --pass QwerTy --dns elasticsearch --out /certs/elasticsearch.p12 &&

          echo "Generating certificate for Kibana" &&
          bin/elasticsearch-certutil cert --silent --ca-cert /certs/ca/ca.crt --ca-key /certs/ca/ca.key --ca-pass QwerTy --pass QwerTy --pem --dns kibana --out /certs/kibana.zip &&
          unzip /certs/kibana.zip -d /certs &&

          mv /certs/instance/instance.crt /certs/kibana.crt &&
          mv /certs/instance/instance.key /certs/kibana.key &&
          rm -rf /certs/instance &&
          chown -R 1000:0 /certs 
  
        fi;
       '
    user: "0"
    working_dir: /usr/share/elasticsearch
    volumes:
      - ./elasticsearch/certs:/certs
    networks:
      - elastic

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch
    environment:
      - COMPOSE_TIMEOUT=20
      - node.master=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - network.host=0.0.0.0
      - node.name=elasticsearch 
      - discovery.seed_hosts=["127.0.0.1"]
      - xpack.security.enabled=true
      - xpack.security.authc.token.enabled=true
      - xpack.security.audit.enabled=true
      - xpack.security.authc.realms.file.file1.order=0
      - xpack.security.authc.realms.native.native1.order=1
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.keystore.password=QwerTy
      - xpack.security.transport.ssl.truststore.password=QwerTy
      - xpack.security.transport.ssl.keystore.path=certs/elasticsearch.p12
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.keystore.password=QwerTy
      - xpack.security.http.ssl.truststore.password=QwerTy
      - xpack.security.http.ssl.keystore.path=certs/elasticsearch.p12
      - xpack.security.http.ssl.verification_mode=certificate
      - xpack.license.self_generated.type=trial
      - ELASTIC_PASSWORD=changeme
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
    networks:
      - elastic
    depends_on:
      - "create_cert"
    volumes:
      - ./elasticsearch/certs:/usr/share/elasticsearch/config/certs
      - elastic-lv:/usr/share/elasticsearch/data
      - elastic-lv:/usr/share/elasticsearch/logs

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.14.0
    environment:
      - COMPOSE_TIMEOUT=20
      - ELASTICSEARCH_HOSTS=["https://elasticsearch:9200"]
      - ELASTICSEARCH_URL=https://elasticsearch:9200
      - XPACK_SECURITY_ENABLED=true
      - ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt
      - ELASTICSEARCH_SSL_VERIFICATIONMODE=certificate
      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_KEY=config/certs/kibana.key
      - SERVER_SSL_CERTIFICATE=config/certs/kibana.crt
      - SERVER_SSL_PASSWORD=QwerTy
      - SERVER_SSL_KEYPASSPHRASE=QwerTy
      - XPACK_SECURITY_ENCRYPTIONKEY=aqwqdqwdkoijiojqwdqwdq133wedqqe2
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    ports:
      - 5601:5601
    depends_on:
      - "create_cert"
      - "elasticsearch"
    links: ['elasticsearch']
    networks:
      - elastic
    volumes:
      - ./elasticsearch/certs:/usr/share/kibana/config/certs
      - elastic-lv:/usr/share/kibana/data
      - elastic-lv:/usr/share/kibana/logs   
networks:
  elastic:
    driver: bridge
volumes: 
  elastic-lv:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./
